name: demo
channels:
  - conda-forge
  - pytorch
  - nvidia
dependencies:
  - python >= 3.10
  - pip
  - cmake
  - dlib
  - ffmpeg
  - ffmpeg-python
  - future
  - imageio
  - imutils
  - networkx
  - numpy
  - packaging
  - Pillow
  - pyparsing
  - django
  - click
  - PyWavelets
  - scikit-image
  - tifffile
  - opencv
  - pytorch=1.13.0
  - cudatoolkit=11.6
  - torchvision=0.14.0
  - pip:
    - PyYAML
    - pandas
    - tabulate
    - scikit-learn
    - scikit-image
    - scipy
    - pyparsing
    - cycler
    - matplotlib
    - facenet_pytorch
    - tqdm
    - oulumetrics  
    - click
