# Execute pair csv generation
python -m ControlledMorphGeneration.MorphGeneration_SimpleSimilarity.t_sne_sample_set_extraction > ControlledMorphGeneration/MorphGeneration_SimpleSimilarity/t_sne_sample_set_extraction.out

# Execute morph generation with csv
python -m ControlledMorphGeneration.MorphGeneration_SimpleSimilarity.ControlledMorphGeneration > ControlledMorphGeneration/MorphGeneration_SimpleSimilarity/ControlledMorphGeneration.out